#version: '3.3'
#
#services:
#  mysql:
#    image: mysql:5.7.31
#    restart: always
#    environment:
#      MYSQL_DATABASE: 'raft_uat'
#      MYSQL_USER: 'root'
#      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
#    ports:
#      - '3306:3306'
#    expose:
#      - '3306'
#    volumes:
#      - my-db:/var/lib/mysql
#  rabbitmq:
#    image: rabbitmq:3-management-alpine
#    restart: always
#    container_name: 'rabbitmq'
#    ports:
#        - 5672:5672
#        - 15672:15672
#    expose:
#        - 15671-15671
#    volumes:
#        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
#        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
#    networks:
#        - rabbitmq_go_net
#volumes:
#  my-db:
#
#networks:
#  rabbitmq_go_net:
#    driver: bridge
#
#
#
#
