application:
    file:
        csv:
            filename: RAFTCSV
            format: .csv
        excel:
            filename: RAFTEXCEL
            format: .xlsx
            sheetname: DetailsSheet
        path: /home/ojas/raft/RAFT-Java/src/main/resources/files
    password:
        expiry:
            time: 30
        forgotpassword:
            url: http://localhost:4200/#/resetPassword
rabbitmq:
    exchange: raft_v1-exchange
    queueName: raft_v1-queue
    routingkey: raft_v1-key
server:
    port: 9999
spring:
    application:
        name: RAFTAPPLICATION
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/raft_uat?createDatabaseIfNotExist=true
        username: root
    flyway:
        baseline-on-migrate: true
        locations: classpath:/db/migration
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5Dialect
                format_sql: true
        show-sql: true
    main:
        allow-bean-definition-overriding: true
